# Generated by Django 5.1 on 2024-08-30 23:14

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('activo', models.CharField(max_length=255)),
                ('portafolio_1', models.DecimalField(max_digits=10, decimal_places=3)),
                ('portafolio_2', models.DecimalField(max_digits=10, decimal_places=3)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
                ('eeuu', models.DecimalField(max_digits=10, decimal_places=4)),
                ('europa', models.DecimalField(max_digits=10, decimal_places=4)),
                ('japon', models.DecimalField(max_digits=10, decimal_places=4)),
                ('em_asia', models.DecimalField(max_digits=10, decimal_places=4)),
                ('latam', models.DecimalField(max_digits=10, decimal_places=4)),
                ('high_yield', models.DecimalField(max_digits=10, decimal_places=4)),
                ('ig_corporate', models.DecimalField(max_digits=10, decimal_places=4)),
                ('emhc', models.DecimalField(max_digits=10, decimal_places=4)),
                ('latam_hy', models.DecimalField(max_digits=10, decimal_places=4)),
                ('uk', models.DecimalField(max_digits=10, decimal_places=4)),
                ('asia_desarrollada', models.DecimalField(max_digits=10, decimal_places=4)),
                ('emea', models.DecimalField(max_digits=10, decimal_places=4)),
                ('otros_rv', models.DecimalField(max_digits=10, decimal_places=4)),
                ('tesoro', models.DecimalField(max_digits=10, decimal_places=4)),
                ('mbs_cmbs_ambs', models.DecimalField(max_digits=10, decimal_places=4)),
                ('abs', models.DecimalField(max_digits=10, decimal_places=4)),
                ('mm_caja', models.DecimalField(max_digits=10, decimal_places=4)),
            ],
        ),
    ]
